# Generated by Codex.
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=160, unique=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=240, verbose_name="标题")),
                ("summary", models.TextField(verbose_name="摘要")),
                ("cover_url", models.CharField(blank=True, max_length=500, verbose_name="封面 URL")),
                ("html_path", models.CharField(max_length=500, verbose_name="HTML 相对路径")),
                ("pub_date", models.DateField(verbose_name="发布时间")),
                ("updated_date", models.DateField(blank=True, null=True, verbose_name="更新时间")),
                ("category", models.CharField(blank=True, max_length=80, verbose_name="分类")),
                ("featured", models.BooleanField(default=False, verbose_name="精选")),
                ("draft", models.BooleanField(default=False, verbose_name="草稿")),
                ("word_count", models.PositiveIntegerField(default=0, verbose_name="文本字数")),
                ("source_hash", models.CharField(blank=True, max_length=64, verbose_name="源文件哈希")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="同步时间")),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-pub_date", "-updated_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="名称")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArticleViewCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_count",
                        to="articles.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章浏览量",
                "verbose_name_plural": "文章浏览量",
            },
        ),
        migrations.CreateModel(
            name="ArticleViewEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visitor_hash", models.CharField(max_length=64, verbose_name="访客哈希")),
                ("view_date", models.DateField(verbose_name="浏览日期")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="articles.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章浏览事件",
                "verbose_name_plural": "文章浏览事件",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="articles", to="articles.tag", verbose_name="标签"),
        ),
        migrations.AddIndex(
            model_name="articleviewevent",
            index=models.Index(fields=["article", "view_date"], name="articles_ar_article_fa66b5_idx"),
        ),
        migrations.AddConstraint(
            model_name="articleviewevent",
            constraint=models.UniqueConstraint(fields=("article", "visitor_hash", "view_date"), name="unique_article_visitor_per_day"),
        ),
    ]
