# Generated by Django 5.2.15 on 2026-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('resource_url', models.CharField(help_text='Use /resource/... or an absolute URL.', max_length=500, verbose_name='Resource URL')),
                ('alt_text', models.CharField(blank=True, max_length=240, verbose_name='Alt text')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('kind', models.CharField(blank=True, max_length=80, verbose_name='Kind')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Media asset',
                'verbose_name_plural': 'Media assets',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('home', 'Home'), ('about', 'About'), ('lab', 'Lab'), ('now', 'Now')], max_length=80, unique=True, verbose_name='Key')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.JSONField(default=dict, verbose_name='Published content')),
                ('draft_content', models.JSONField(blank=True, default=dict, verbose_name='Draft content')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Site page',
                'verbose_name_plural': 'Site pages',
                'ordering': ['key'],
            },
        ),
    ]
