# Generated by Django 5.2.15 on 2026-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_mediaasset_sitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='HTML 正文'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_markdown',
            field=models.TextField(blank=True, verbose_name='Markdown 草稿'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_source',
            field=models.CharField(choices=[('resource', 'Resource folder'), ('manual', 'Manual entry')], default='resource', max_length=20, verbose_name='内容来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='HTML 相对路径'),
        ),
    ]
